import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  devGuideSidebar: [{type: 'autogenerated', dirName: 'dev-guide'}],
  gameManualSidebar: [{type: 'autogenerated', dirName: 'game-manual'}],
};

export default sidebars;
